name: Release
# Invocable as a reusable workflow
# Can be manually triggered
on:
  workflow_dispatch:
  workflow_call:

jobs:
  csm-release:
    name: Releases Driver
    runs-on: ubuntu-latest
    steps:
      - name: Checkout the code
        uses: dell/common-github-actions/csm-release@reusuable-release-workflow
