name: Release
# Invocable as a reusable workflow
# Can be manually triggered
on:
  workflow_dispatch:
  workflow_call:

jobs:

  csm-release:
    uses: dell/common-github-actions/.github/workflows/csm-release.yaml@reusuable-release-workflow
    name: Releases Driver
